language: haskell
ghc:
- 7.8
- 7.6
install:
  - cabal install --only-dependencies --enable-tests --constraint mtl==2.1.2
script:
  - cabal configure --enable-tests && cabal build && dist/build/tests/tests
deploy:
  provider: hackage
  username: Bodigrim
  password:
    secure: HyyrFipAMQ+OjDdQrIdGRsrAzd4HsRG+QnRbDtButTAP0SP2xQzBQ7HXpaEKgwvt9iHeISo/oXubRZlOc0KifzSl0LRb62pCqOEhM7dyH/6hGv/8qgXIKnDakQ8XcRASdme/nYkShpbm++7CIadV2OmETx3yQRfmJPVptkJnx78=
  on:
    repo: Bodigrim/exp-pairs
