name:                 exp-pairs
version:              0.2.1.1
visibility:           public
id:                   exp-pairs-0.2.1.1-inplace
key:                  exp-pairs-0.2.1.1-inplace
license:              GPL-3.0-only
maintainer:           andrew.lelechenko@gmail.com
author:               Andrew Lelechenko
homepage:             https://github.com/Bodigrim/exp-pairs
synopsis:             Linear programming over exponent pairs
description:
    Package implements an algorithm to minimize rational objective function over the set of exponent pairs

category:             Math
abi:                  inplace
exposed:              True
exposed-modules:
    Math.ExpPairs Math.ExpPairs.Ivic Math.ExpPairs.Kratzel
    Math.ExpPairs.LinearForm Math.ExpPairs.Matrix3
    Math.ExpPairs.MenzerNowak Math.ExpPairs.Pair
    Math.ExpPairs.PrettyProcess Math.ExpPairs.Process
    Math.ExpPairs.ProcessMatrix Math.ExpPairs.RatioInf

import-dirs:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/build

library-dirs:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/build

library-dirs-static:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/build

dynamic-library-dirs:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/build

data-dir:             /home/runner/work/exp-pairs/exp-pairs/.
hs-libraries:         HSexp-pairs-0.2.1.1-inplace
depends:
    base-4.22.0.0-fde1 containers-0.8-89c1 deepseq-1.5.1.0-f671
    ghc-prim-0.13.1-b3ca
    prettyprinter-1.7.2-409bed2f28289257571278b8ab34f5d922db112bb1b0164d9eab0f26e82629cc

haddock-interfaces:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/doc/html/exp-pairs/exp-pairs.haddock

haddock-html:
    /home/runner/work/exp-pairs/exp-pairs/dist-newstyle/build/x86_64-linux/ghc-9.14.1/exp-pairs-0.2.1.1/doc/html/exp-pairs
